import turtle

STANDARD_LOGO_SIZE = 256

def draw_logo(x, y, scale = 1, angle = 0):
    turtle.penup()
    turtle.goto(x, y)
    turtle.setheading(angle)
    turtle.forward(scale * 128)
    turtle.right(180)
    turtle.circle(scale * 128, 180)
    turtle.pendown()
    turtle.pensize(3)
    turtle.circle(scale * 128, 360)
    turtle.penup()
    turtle.left(90)
    turtle.forward(scale * 6)
    turtle.right(90)
    turtle.pendown()
    turtle.pensize(2)
    turtle.circle(scale * 121.8, 300)
    turtle.pensize(2)

    for _ in range(3):
        turtle.circle(scale * 121.8, 120)
        turtle.begin_fill()
        turtle.left(97.5)
        turtle.forward(scale * 112)
        turtle.right(67.5)
        turtle.forward(scale * 15)
        turtle.right(120)
        turtle.forward(scale * 116.88)
        turtle.end_fill()
        turtle.backward(scale * 116.88)
        turtle.left(120)
        turtle.backward(scale * 15)
        turtle.left(67.5)
        turtle.backward(scale * 112)
        turtle.right(15)
        turtle.begin_fill()
        turtle.forward(scale * 112)
        turtle.left(67.5)
        turtle.forward(scale * 15)
        turtle.right(60)
        turtle.backward(scale * 116.88)
        turtle.end_fill()
        turtle.forward(scale * 116.88)
        turtle.left(60)
        turtle.backward(scale * 15)
        turtle.right(67.5)
        turtle.backward(scale * 112)
        turtle.right(82.5)

    turtle.pencolor("White")
    turtle.fillcolor("White")
    turtle.pensize(1)
    turtle.left(90)
    turtle.begin_fill()
    turtle.forward(scale * 119)
    turtle.left(105)
    turtle.forward(scale * 10)
    turtle.left(80)
    turtle.forward(scale * 117)
    turtle.end_fill()
    turtle.penup()
    turtle.pencolor("Black")
    turtle.backward(scale * 117)
    turtle.right(80)
    turtle.backward(scale * 10)
    turtle.fillcolor("Black")
    turtle.begin_fill()
    turtle.left(10)
    turtle.pendown()
    turtle.forward(scale * 5)
    turtle.left(70)
    turtle.forward(scale * 20)
    turtle.left(170)
    turtle.forward(scale * 23)
    turtle.end_fill()
    
    turtle.penup()
    turtle.backward(scale * 23)
    turtle.right(170)
    turtle.backward(scale * 20)
    turtle.right(70)
    turtle.backward(scale * 5)
    turtle.right(10)
    turtle.forward(scale * 10)
    turtle.left(80)
    turtle.forward(scale * 117)
    turtle.backward(scale * 117)
    turtle.right(80)
    turtle.backward(scale * 10)
    turtle.right(105)
    turtle.backward(scale * 119)
    turtle.right(90)
    turtle.circle(scale * 121.8, 240)
    turtle.pendown()
    
    turtle.pencolor("White")
    turtle.fillcolor("White")
    turtle.pensize(1)
    turtle.left(90)
    turtle.begin_fill()
    turtle.forward(scale * 119)
    turtle.right(105)
    turtle.forward(scale * 10)
    turtle.right(80)
    turtle.forward(scale * 117)
    turtle.end_fill()
    turtle.penup()
    turtle.pencolor("Black")
    turtle.backward(scale * 117)
    turtle.left(80)
    turtle.backward(scale * 10)
    turtle.fillcolor("Black")
    turtle.begin_fill()
    turtle.right(10)
    turtle.pendown()
    turtle.forward(scale * 8)
    turtle.right(69.5)
    turtle.forward(scale * 78)
    turtle.right(176)
    turtle.forward(scale * 40)
    turtle.end_fill()

